-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.noice")
require("config.neo-tree")
require("config.lualine")
require("config.tailwindcss")
require("config.telescope")
require("config.autocmd")
require("config.keymaps")
require("config.options")
require("config.lazygit")
